### ISSUE TITLE
Should we "unite" exceptions which are critical?

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#136]
There are some exceptions that catching them in GUI level means something went REALLY wrong - critical errors. 
I though to let those kinds of exceptions extend CriticalError exception class. What do think?
(For example, invalid cmd descriptor & invalid parameter requires the handling of a critical error)
@AviadCo @shimonAzulay @LiorBenAmi @noamyft

**Comment by yossigil** [comment]
Take a look at class 'fault' and at class 'monitor' in the spartanizer project. don't just look at the classes, but also at the way they are used within assertions and within catch blocks.

They offer a mechanism for managing problems such as this: faults due to massive inexplicable errors such as the one you may need to worry about.

Feel free to copy and mutilate in any way

**Comment by IdanAtias** [comment]
OK, thanks. I'll have a look at this.
