### ISSUE TITLE
Add Client-Server communication

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#187]
add commands descriptor, results descriptor, exceptions...
#185

**Comment by LiorBenAmi** [comment]
@AviadCo I added the commands we had talked about. Need to implement them on the server side

**Comment by AviadCo** [comment]
Hi Lior,

1. Please move 'Grocery List' class to common since the server should also use the same class.
2. in cartImplementation use only function which are in ICart (no need other to implement those, if you think there is need for it make in private - the idea of ICart is that the GUI will know which functions it can use without seeing the implementations).
3. There is no need to use cartProduct - use ProductPackage (we move ProductPackage from shelves to the buying list, all the needed information is in ProductPackage and it easier to mantain).
4. When you are making commits, please do the minimal changes to files. i.e. in CommandDescriptor you changed all the file and it is very hard to know what's added/removed now... (i think you use ctrl + shift +f) on the file).
5. I don't really have time to over the commands until saturday, @noamyft @IdanAtias please go over the new command for cart and new result and say what you think.

**Comment by LiorBenAmi** [comment]
1+2. ok
3. I don't agree with you. I want the gui to present each of the grocery list in the cart. In CartProduct you have CatalogProduct so it got the products info to present. In ProductPackage you got Smart Code so you got to do server request to get the CatalogProduct every time you want to present it.
4. Ok, The change was to place the java doc above its method so you can read it from another files.

**Comment by AviadCo** [comment]
regarding 3 - if you choose to use new structures, you must ask Noam if the SQL supports or something else is already implemented... moreover, i don't think we should send all to information of the product to the cart unless the GUI (the customer) wants to see it... it will cost to send a lot of data on the wire which we should be alert from....
4. Please see that the order of javadoc is the same in ResultDecriptor (i changed the order once to make them equal).

**Comment by LiorBenAmi** [comment]
@AviadCo CartProduct isn't new. we agreed on it on the first design. also agreed that grocery list will be a collection of CartProduct.
@noamyft  Is it ok with you?

**Comment by noamyft** [comment]
@LiorBenAmi you can use CartProduct in the grocery list (especially because the cart dont need "location")
But Aviad raise good issue: if the CartProduct contain CatalogProduct in it, and  when you request the list, the server need to create all that CatalogProduct, and send all that data at once - It may slow the server

לכן אני חושב שכדאי שבכל התקשורת עם ומהשרת - נעבוד עם סמארטקודים (ולכן צריך לשנות את CARTPRODUCT)
בנוגע להצגה של הפריטים בתוכנה של העגלה - אני חושב שבכל מקרה זה יותר יעיל ויותר כדאי לשמור רשימה נפרדת של המוצרים בקטלוג (רק אלה שמופיעים ברשימה - מעיין קאש כזה..) וכך בכל פעם שאתה צריך לשלוף מידע עבור מוצר מסויים - אתה ניגש לשם

(ללא קשר לעיל, אני חושב שחלק מהפרטים על המוצר צריכים להופיע ברשימה עצמה וכל הפרטים יחשפו כאשר תלחץ על המוצר ברשימה)

Sorry for my hebrew... :)

**Comment by LiorBenAmi** [comment]
@noamyft  yeah that was my idea. 
Ok your solution is fine by me. I'll change the GroceryList Type to contain SmartCodes and different cache of CartProducts
