### ISSUE TITLE
Find solution to implement SmartCode

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#24]
Understand if a barcode can be extended to include also expiration date of the product or find another solution for implementing SmartCode

**Comment by noamyft** [comment]
we can't use the Symbology used nowadays in products in supermarkets, because this method (called EAN-8, EAN-13) is limited to 13 digit (of the product itself) + 5 additional digits (not enough for expiration date and the app not recognizing it).
we have to use GS1-128 Symbology, richer and not length limited symbology.

references:

- gs1-128 code generator (with fields checking)
https://www.free-barcode-generator.net/ean-128/

- explanation of gs1-128 format - wikipedia
https://en.wikipedia.org/wiki/GS1-128

- gs1-128 - official site
http://www.gs1-128.info/application-identifiers/

- code 123 coding - wikipedia
https://en.wikipedia.org/wiki/Code_128

**Comment by AviadCo** [comment]
Great job. 
I opened Wiki for SmartCode based on this information.
