### ISSUE TITLE
Refactor in LOG 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#427]
Add to your catch block the following code 

`log.debug(e.getStackTrace());
 log.fatal(e.getMessage());`
(e is the exception instance)
The first print to log will be the message came from the exception while the second will be the stack trace.

@TomPalny  
What do you think about this?

I am doing a refactor right now #426 with the GUI exceptions so it will be easy to print the error to screen and show them to the user. 
So after i finish this, each of you should do the changes in the GUI code you wrote.

**Comment by TomPalny** [comment]
The log's highest reason of existence is to allow the user to recover
gracefully from errors.
So, if in this case it is used for debugging only, you would be ok. In any
other case, I suggest to take a look at logging levels as described in this
document:

https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html

בתודה,
תום

On May 15, 2017 17:12, "Shimon Azulay" <notifications@github.com> wrote:

Add to your catch block the following code

log.debug(e.getStackTrace()); log.fatal(e.getMessage());
(Where e is the exception instance)
The first print to log will be the message came from the exception while
the second will be the stack trace.

@TomPalny <https://github.com/tompalny>
What do you think about this?

I am doing a refactor right now #426
<https://github.com/TechnionYP5777/SmartCity-Market/issues/426> with the
GUI exceptions so it will be easy to print the error to screen and show to
the user.
So after i finish this, each of you should do the changes in the GUI code
you wrote.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TechnionYP5777/SmartCity-Market/issues/427>, or mute
the thread

**Comment by shimonAzulay** [comment]
TODO Handle log file creation errors from modules without GUI
